# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Releases

on:
  push:
    branches: [ v1 ]

jobs:
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.fetch-release-version.outputs.release-version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch release version
        id: fetch-release-version
        run: echo "::set-output name=release-version::$(cat pom.xml | sed -n 's/  <version>\(.*\)<\/version>/\1/p; /version>/q')"

  build-windows:
    runs-on: windows-latest
    needs:
      - determine-version
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install MSVC
        uses: ilammy/msvc-dev-cmd@v1.5.0

      - name: Setup MS Build Tools
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          # GraalVM version, no pattern syntax available atm
          graalvm: '21.3.0'
          # Java version, optional, defaults to 'java8'. Available options are 'java8' and 'java11'.
          java: 'java11'
          # Architecture flag, optional, defaults to 'amd64'. Available options are 'amd64' and 'aarch64'. Later is available only for linux runners.
          arch: 'amd64'

      - name: Install native-image component
        run: gu.cmd install native-image

      - name: Download and install Inno Setup
        run: |
          curl.exe -o innosetup-6.2.0.exe https://files.jrsoftware.org/is/6/innosetup-6.2.0.exe
          innosetup-6.2.0.exe /VERYSILENT /NORESTART /ALLUSERS
          echo "C:\Program Files (x86)\Inno Setup 6" >> $GITHUB_PATH
        shell: cmd

      - name: Create app config for building
        run: copy src\main\resources\config.sample src\main\resources\application.yaml
        shell: cmd
      
      - name: Build native-image release
        run: mvn clean generate-resources compile package -Pnative
      
      - name: Rename executable
        run: |
          cd target
          rename plexbot-encoder-runner.exe plexbot-encoder-win64.exe
        shell: cmd

      - name: Prep installer build files
        run: |
          copy target\plexbot-encoder-win64.exe installer
          cd installer
          curl -o ffmpeg.zip -L https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2022-01-11-12-22/ffmpeg-N-105258-g3c2b674468-win64-gpl.zip
          tar -xf ffmpeg.zip --strip-components 2 *.exe
          del ffmpeg.zip
        shell: cmd

      - name: Build Installer
        run: |
          cd installer
          iscc plexbot-installer-config.iss
        shell: cmd
        env:
          RELEASE_VERSION: ${{ needs.determine-version.outputs.release-version }}

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: plexbot-encoder-win64.exe
          path: target\plexbot-encoder-win64.exe
          retention-days: 1

      - name: Upload installer
        uses: actions/upload-artifact@v2
        with:
          name: plexbot-encoder_v${{ needs.determine-version.outputs.release-version }}.exe
          path: installer\Output\plexbot-encoder_v${{ needs.determine-version.outputs.release-version }}.exe
          retention-days: 1
        
  build-macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          # GraalVM version, no pattern syntax available atm
          graalvm: '21.3.0'
          # Java version, optional, defaults to 'java8'. Available options are 'java8' and 'java11'.
          java: 'java11'
          # Architecture flag, optional, defaults to 'amd64'. Available options are 'amd64' and 'aarch64'. Later is available only for linux runners.
          arch: 'amd64'

      - name: Install native-image component
        run: gu install native-image

      - name: Create app config for building
        run: cp src/main/resources/config.sample src/main/resources/application.yaml
      
      - name: Build native-image release
        run: mvn clean generate-resources compile package -Pnative
      
      - name: Rename executable
        run: mv target/plexbot-encoder-runner target/plexbot-encoder-darwin64
        
      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: plexbot-encoder-darwin64
          path: target/plexbot-encoder-darwin64
          retention-days: 1
        
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          # GraalVM version, no pattern syntax available atm
          graalvm: '21.3.0'
          # Java version, optional, defaults to 'java8'. Available options are 'java8' and 'java11'.
          java: 'java11'
          # Architecture flag, optional, defaults to 'amd64'. Available options are 'amd64' and 'aarch64'. Later is available only for linux runners.
          arch: 'amd64'

      - name: Install native-image component
        run: gu install native-image

      - name: Create app config for building
        run: cp src/main/resources/config.sample src/main/resources/application.yaml
      
      - name: Build native-image release
        run: mvn clean generate-resources compile package -Pnative
      
      - name: Rename executable
        run: mv target/plexbot-encoder-runner target/plexbot-encoder-linux64
        
      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: plexbot-encoder-linux64
          path: target/plexbot-encoder-linux64
          retention-days: 1

  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          # GraalVM version, no pattern syntax available atm
          graalvm: '21.3.0'
          # Java version, optional, defaults to 'java8'. Available options are 'java8' and 'java11'.
          java: 'java11'
          # Architecture flag, optional, defaults to 'amd64'. Available options are 'amd64' and 'aarch64'. Later is available only for linux runners.
          arch: 'amd64'

      - name: Create app config for building
        run: cp src/main/resources/config.sample src/main/resources/application.yaml
      
      - name: Build jar release
        run: mvn clean generate-resources compile package -Puber
      
      - name: Rename jar
        run: mv target/plexbot-encoder-runner.jar target/plexbot-encoder.jar
        
      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: plexbot-encoder.jar
          path: target/plexbot-encoder.jar
          retention-days: 1

  create-release:
    runs-on: ubuntu-latest
    needs:
      - determine-version
      - build-windows
      - build-macOS
      - build-linux
      - build-jar
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Download windows executable
        uses: actions/download-artifact@v2
        with:
          name: plexbot-encoder-win64.exe

      - name: Download Windows Installer
        uses: actions/download-artifact@v2
        with:
          name: plexbot-encoder_v${{ needs.determine-version.outputs.release-version }}.exe
          
      - name: Download macOS executable
        uses: actions/download-artifact@v2
        with:
          name: plexbot-encoder-darwin64
    
      - name: Download linux executable
        uses: actions/download-artifact@v2
        with:
          name: plexbot-encoder-linux64

      - name: Download jar
        uses: actions/download-artifact@v2
        with:
          name: plexbot-encoder.jar
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ needs.determine-version.outputs.release-version }}
          tag_name: ${{ needs.determine-version.outputs.release-version }}
          draft: true
          prerelease: false
          files: |
            plexbot-encoder-win64.exe
            plexbot-encoder_v${{ needs.determine-version.outputs.release-version }}.exe
            plexbot-encoder-darwin64
            plexbot-encoder-linux64
            plexbot-encoder.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
